#!/usr/bin/env sh
#
# see: https://www.josean.com/posts/yabai-setup
# also:
#   https://github.com/koekeishiya/yabai
#   https://github.com/koekeishiya/yabai/wiki
#   https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc
#
# brew install koekeishiya/formulae/yabai
# yabai --start-service
# yabai --restart-service
#
# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# mission-control desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label work
yabai -m space 3 --label mail
yabai -m space 4 --label notes
yabai -m space 5 --label etc

# specific space settings
yabai -m config --space mail  layout stack
yabai -m config --space notes layout stack
yabai -m config --space etc   layout float

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 2px
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 2

# mouse follow focus
yabai -m config mouse_follows_focus off

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier fn

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window
yabai -m config mouse_action1 resize
# set modifier + right-click drag to move window
yabai -m config mouse_action2 move
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5

# window rules
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add app!="Terminal|iTerm|iTerm2|Safari|Firefox" manage=off sticky=on sub-layer=above
yabai -m rule --add app="^Mail$" title=".*" space=^mail manage=on sticky=off
yabai -m rule --add app="^Safari$" space=^web 
yabai -m rule --add app="^Firefox$" space=^web
yabai -m rule --add app="^Terminal$" space=^work
yabai -m rule --add app="^iTerm2$" space=^work 
yabai -m rule --add app="^Notizen$" title!="^Neue Notiz$" space=^notes manage=on sticky=off
yabai -m rule --add app="^Notizen$" title="^Neue Notiz$" manage=off sticky=on sub-layer=above

